// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xjk2ggDqJmDLYHcQyob5H68xhSZkCMU',
    appId: '1:184427287724:web:a69f71cc09f2d267f4bb09',
    messagingSenderId: '184427287724',
    projectId: 'finesight-ai',
    authDomain: 'finesight-ai.firebaseapp.com',
    storageBucket: 'finesight-ai.firebasestorage.app',
    measurementId: 'G-TY88QC453G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP112ZNwgIy7T8RL1w5BbTTOpa4y0UuRg',
    appId: '1:184427287724:android:89c704bfc7846667f4bb09',
    messagingSenderId: '184427287724',
    projectId: 'finesight-ai',
    storageBucket: 'finesight-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6A5tLEYBxFqBY3lOZ9GQWQEAfC-tnJQ',
    appId: '1:184427287724:ios:c0017a55283177a5f4bb09',
    messagingSenderId: '184427287724',
    projectId: 'finesight-ai',
    storageBucket: 'finesight-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc6A5tLEYBxFqBY3lOZ9GQWQEAfC-tnJQ',
    appId: '1:184427287724:ios:c0017a55283177a5f4bb09',
    messagingSenderId: '184427287724',
    projectId: 'finesight-ai',
    storageBucket: 'finesight-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1xjk2ggDqJmDLYHcQyob5H68xhSZkCMU',
    appId: '1:184427287724:web:f5f39ea94c4c7971f4bb09',
    messagingSenderId: '184427287724',
    projectId: 'finesight-ai',
    authDomain: 'finesight-ai.firebaseapp.com',
    storageBucket: 'finesight-ai.firebasestorage.app',
    measurementId: 'G-F6NX7QGKLH',
  );
}
